/*
 * GUIDBMStoreProductForm.java
 *
 * This class provides a form for adding or modifying a store-product record.
 */

package edu.byu.isys413.group1a.intex2.GUIs;
import edu.byu.isys413.group1a.intex2.BOs.StoreProduct;
import edu.byu.isys413.group1a.intex2.Controllers.DBMStoreProductController;
import javax.swing.DefaultComboBoxModel;
import javax.swing.UIManager;
import javax.swing.JOptionPane;

/**
 *
 * @author Aaron Hardy, Section 1A, me@aaronhardy.com
 *
 */
public class GUIDBMStoreProductForm extends javax.swing.JFrame {
  
  private GUIDBMStoreProductDisplay display;
  private DBMStoreProductController controller;
  private StoreProduct storeProduct;  
  
  /** Creates new form for adding a store-video record */
  public GUIDBMStoreProductForm(GUIDBMStoreProductDisplay display, DBMStoreProductController controller) {
    loadGUI();
    this.display = display;
    this.controller = controller;
    addModifyButton.setText("Add Store Product");
    
    try{
      storeBox.setModel(controller.getStoreModel());
      productBox.setModel(controller.getProductModel());
    } catch (Exception e) {
      JOptionPane.showMessageDialog(this, "An error occured while loading form information.", "Error Loading Form Info", JOptionPane.ERROR_MESSAGE);
    }
  }
  
  /** Creates new form for modifying a store-product record */
  public GUIDBMStoreProductForm(GUIDBMStoreProductDisplay display, DBMStoreProductController controller, int rowNumber) {
    loadGUI();
    this.display = display;
    this.controller = controller;
    addModifyButton.setText("Modify Rental Video");
    storeProduct = controller.getStoreProductList().get(rowNumber);
    
    try{
      storeBox.setModel(controller.getStoreModel());
      storeBox.setSelectedIndex(controller.getModelIndex(storeProduct.getStore(),storeBox.getModel()));
      productBox.setModel(controller.getProductModel());
      productBox.setSelectedIndex(controller.getModelIndex(storeProduct.getProd(),productBox.getModel()));
      qohField.setText(storeProduct.getQtyOnHand()+"");
      reorderPointField.setText(storeProduct.getReorderPoint()+"");
      reorderQuantityField.setText(storeProduct.getReorderQTY()+"");
    } catch (Exception e) {
      JOptionPane.showMessageDialog(this, "An error occured while loading form information.", "Error Loading Form Info", JOptionPane.ERROR_MESSAGE);
    }
  }
  
  private void loadGUI(){
    /* Sets the GUI to the system look and feel  */
    try {
      UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
    } catch (Exception e) {
      System.err.println("Error loading look and feel: " + e);
    }
    
    initComponents();
    
  }
  
  /*
  // Method for checking uniqueness of foreign keys 
  private boolean foreignKeysUniqueCheck(){
    // if modifying rental video and serial # hasn't changed, there's no need to check
    if (rentalVideo != null){
      if (serialNumberField.getText().equals(rentalVideo.getSerialNum())){
        return true;
      }
    }
    
    try {
      StoreProductDAO.getInstance().readByForeign(storeProduct.getStore().getId(), storeProduct.getProd().getId())
      JOptionPane.showMessageDialog(this, "The product " + storeProduct.getProd().getDescription() + " at the store  " already exists.", "Duplicate Rental Video", JOptionPane.ERROR_MESSAGE);
      return false;
    } catch (DataException de){
      return true; // This means there was no rental video with the given serial number.  Good to go.
    }
  }
   */
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
  private void initComponents() {
    mainScrollPanel = new javax.swing.JScrollPane();
    jPanel1 = new javax.swing.JPanel();
    mainPanel = new javax.swing.JPanel();
    transactionPanel = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    productBox = new javax.swing.JComboBox();
    addModifyButton = new javax.swing.JButton();
    cancelButton = new javax.swing.JButton();
    storeBox = new javax.swing.JComboBox();
    qohField = new javax.swing.JTextField();
    reorderPointField = new javax.swing.JTextField();
    reorderQuantityField = new javax.swing.JTextField();
    mainLabelPanel = new javax.swing.JPanel();
    blockWoodLabel = new javax.swing.JLabel();
    logPanel = new javax.swing.JPanel();
    logLabel = new javax.swing.JLabel();
    jSeparator1 = new javax.swing.JSeparator();
    employeeName = new javax.swing.JLabel();
    jSeparator2 = new javax.swing.JSeparator();
    employeeIDLabel = new javax.swing.JLabel();
    employeeID = new javax.swing.JLabel();
    jSeparator4 = new javax.swing.JSeparator();
    logButton = new javax.swing.JToggleButton();
    group1aLabel = new javax.swing.JLabel();
    mainMenuBar = new javax.swing.JMenuBar();
    File = new javax.swing.JMenu();
    login = new javax.swing.JMenuItem();
    logout = new javax.swing.JMenuItem();
    properties = new javax.swing.JMenuItem();
    exit = new javax.swing.JMenuItem();
    Rentals = new javax.swing.JMenu();
    transaction = new javax.swing.JMenuItem();
    checkInVideo = new javax.swing.JMenuItem();
    movieAvailability = new javax.swing.JMenuItem();
    reserveMovie = new javax.swing.JMenuItem();
    Accounts = new javax.swing.JMenu();
    jMenuItem9 = new javax.swing.JMenuItem();
    jMenuItem10 = new javax.swing.JMenuItem();
    jMenuItem11 = new javax.swing.JMenuItem();
    jMenuItem12 = new javax.swing.JMenuItem();
    jMenuItem13 = new javax.swing.JMenuItem();
    jMenuItem14 = new javax.swing.JMenuItem();
    DeleteAccount = new javax.swing.JMenuItem();
    Orders = new javax.swing.JMenu();
    jMenuItem15 = new javax.swing.JMenuItem();
    jMenuItem16 = new javax.swing.JMenuItem();
    jMenuItem17 = new javax.swing.JMenuItem();
    jMenuItem18 = new javax.swing.JMenuItem();
    jMenuItem19 = new javax.swing.JMenuItem();
    Reports = new javax.swing.JMenu();
    jMenuItem5 = new javax.swing.JMenuItem();
    Print = new javax.swing.JMenuItem();
    jMenuItem21 = new javax.swing.JMenuItem();
    jMenuItem22 = new javax.swing.JMenuItem();
    jMenuItem23 = new javax.swing.JMenuItem();
    Help = new javax.swing.JMenu();
    jMenuItem24 = new javax.swing.JMenuItem();
    jMenuItem25 = new javax.swing.JMenuItem();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("BlockWoodVideo");
    setBackground(new java.awt.Color(255, 255, 255));
    transactionPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Store Product Information"));
    jLabel1.setText("Store:");

    jLabel2.setText("Product:");

    jLabel3.setText("Quantity On Hand:");

    jLabel4.setText("Reorder Point:");

    jLabel5.setText("Reorder Quantity:");

    addModifyButton.setText("Add/Modify Store Product");
    addModifyButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        addModifyButtonActionPerformed(evt);
      }
    });

    cancelButton.setText("Cancel");
    cancelButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cancelButtonActionPerformed(evt);
      }
    });

    org.jdesktop.layout.GroupLayout transactionPanelLayout = new org.jdesktop.layout.GroupLayout(transactionPanel);
    transactionPanel.setLayout(transactionPanelLayout);
    transactionPanelLayout.setHorizontalGroup(
      transactionPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(transactionPanelLayout.createSequentialGroup()
        .add(21, 21, 21)
        .add(transactionPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
          .add(jLabel4)
          .add(jLabel5)
          .add(jLabel2)
          .add(jLabel3)
          .add(jLabel1))
        .add(17, 17, 17)
        .add(transactionPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
          .add(reorderQuantityField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
          .add(reorderPointField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
          .add(qohField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
          .add(storeBox, 0, 257, Short.MAX_VALUE)
          .add(productBox, 0, 257, Short.MAX_VALUE)
          .add(org.jdesktop.layout.GroupLayout.TRAILING, transactionPanelLayout.createSequentialGroup()
            .add(addModifyButton)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(cancelButton)))
        .add(65, 65, 65))
    );
    transactionPanelLayout.setVerticalGroup(
      transactionPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(transactionPanelLayout.createSequentialGroup()
        .addContainerGap()
        .add(transactionPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(jLabel1)
          .add(storeBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        .add(22, 22, 22)
        .add(transactionPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(jLabel2)
          .add(productBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        .add(23, 23, 23)
        .add(transactionPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(jLabel3)
          .add(qohField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        .add(23, 23, 23)
        .add(transactionPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(jLabel4)
          .add(reorderPointField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        .add(21, 21, 21)
        .add(transactionPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(jLabel5)
          .add(reorderQuantityField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        .add(26, 26, 26)
        .add(transactionPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(addModifyButton)
          .add(cancelButton))
        .addContainerGap(33, Short.MAX_VALUE))
    );

    org.jdesktop.layout.GroupLayout mainPanelLayout = new org.jdesktop.layout.GroupLayout(mainPanel);
    mainPanel.setLayout(mainPanelLayout);
    mainPanelLayout.setHorizontalGroup(
      mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(mainPanelLayout.createSequentialGroup()
        .add(118, 118, 118)
        .add(transactionPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(113, Short.MAX_VALUE))
    );
    mainPanelLayout.setVerticalGroup(
      mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(org.jdesktop.layout.GroupLayout.TRAILING, mainPanelLayout.createSequentialGroup()
        .addContainerGap(22, Short.MAX_VALUE)
        .add(transactionPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        .add(39, 39, 39))
    );
    jPanel1.add(mainPanel);

    mainScrollPanel.setViewportView(jPanel1);

    getContentPane().add(mainScrollPanel, java.awt.BorderLayout.CENTER);

    mainLabelPanel.setLayout(new java.awt.BorderLayout());

    mainLabelPanel.setAutoscrolls(true);
    blockWoodLabel.setBackground(new java.awt.Color(204, 0, 51));
    blockWoodLabel.setFont(new java.awt.Font("Monotype Corsiva", 0, 36));
    blockWoodLabel.setForeground(new java.awt.Color(255, 255, 255));
    blockWoodLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    blockWoodLabel.setText("BlockWood Video Inventory Management");
    blockWoodLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    blockWoodLabel.setMaximumSize(new java.awt.Dimension(627, 45));
    blockWoodLabel.setOpaque(true);
    blockWoodLabel.setPreferredSize(new java.awt.Dimension(412, 50));
    mainLabelPanel.add(blockWoodLabel, java.awt.BorderLayout.NORTH);

    logPanel.setBackground(new java.awt.Color(204, 0, 51));
    logPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
    logPanel.setForeground(new java.awt.Color(255, 255, 255));
    logPanel.setMinimumSize(new java.awt.Dimension(155, 41));
    logPanel.setPreferredSize(new java.awt.Dimension(155, 41));
    logLabel.setBackground(new java.awt.Color(215, 214, 214));
    logLabel.setForeground(new java.awt.Color(255, 255, 255));
    logLabel.setText("Logged in as:");
    logPanel.add(logLabel);

    jSeparator1.setBackground(new java.awt.Color(204, 0, 51));
    jSeparator1.setForeground(new java.awt.Color(204, 0, 51));
    jSeparator1.setPreferredSize(new java.awt.Dimension(25, 10));
    logPanel.add(jSeparator1);

    employeeName.setBackground(new java.awt.Color(215, 214, 214));
    employeeName.setForeground(new java.awt.Color(255, 255, 255));
    employeeName.setText("James Christensen");
    logPanel.add(employeeName);

    jSeparator2.setBackground(new java.awt.Color(204, 0, 51));
    jSeparator2.setForeground(new java.awt.Color(204, 0, 51));
    jSeparator2.setPreferredSize(new java.awt.Dimension(25, 10));
    logPanel.add(jSeparator2);

    employeeIDLabel.setForeground(new java.awt.Color(255, 255, 255));
    employeeIDLabel.setText("Employee ID:");
    logPanel.add(employeeIDLabel);

    employeeID.setForeground(new java.awt.Color(255, 255, 255));
    employeeID.setText("788997");
    logPanel.add(employeeID);

    jSeparator4.setBackground(new java.awt.Color(204, 0, 51));
    jSeparator4.setForeground(new java.awt.Color(204, 0, 51));
    jSeparator4.setPreferredSize(new java.awt.Dimension(25, 10));
    logPanel.add(jSeparator4);

    logButton.setText("Logout");
    logButton.setToolTipText("Logout Current User");
    logButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        logButtonActionPerformed(evt);
      }
    });

    logPanel.add(logButton);

    mainLabelPanel.add(logPanel, java.awt.BorderLayout.SOUTH);

    getContentPane().add(mainLabelPanel, java.awt.BorderLayout.NORTH);

    group1aLabel.setBackground(new java.awt.Color(204, 0, 51));
    group1aLabel.setForeground(new java.awt.Color(255, 255, 255));
    group1aLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    group1aLabel.setText("Created by Group 1A");
    group1aLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    group1aLabel.setMinimumSize(new java.awt.Dimension(100, 25));
    group1aLabel.setOpaque(true);
    group1aLabel.setPreferredSize(new java.awt.Dimension(100, 25));
    getContentPane().add(group1aLabel, java.awt.BorderLayout.SOUTH);

    File.setText("File");
    login.setText("Login");
    File.add(login);

    logout.setText("Logout");
    File.add(logout);

    properties.setText("Properties");
    File.add(properties);

    exit.setText("Exit");
    File.add(exit);

    mainMenuBar.add(File);

    Rentals.setText("Rentals");
    transaction.setText("Make Another Transaction");
    Rentals.add(transaction);

    checkInVideo.setText("Check-in Video");
    Rentals.add(checkInVideo);

    movieAvailability.setText("Check Movie Availability");
    Rentals.add(movieAvailability);

    reserveMovie.setText("Reserve Movie");
    Rentals.add(reserveMovie);

    mainMenuBar.add(Rentals);

    Accounts.setText("Accounts");
    jMenuItem9.setText("Create Customer Membership");
    Accounts.add(jMenuItem9);

    jMenuItem10.setText("Create Customer Account");
    Accounts.add(jMenuItem10);

    jMenuItem11.setText("Update Customer Account");
    Accounts.add(jMenuItem11);

    jMenuItem12.setText("Add Membership to Account");
    Accounts.add(jMenuItem12);

    jMenuItem13.setText("Reissue Membership Card");
    Accounts.add(jMenuItem13);

    jMenuItem14.setText("Search for Account");
    Accounts.add(jMenuItem14);

    DeleteAccount.setLabel("Delete Account");
    Accounts.add(DeleteAccount);

    mainMenuBar.add(Accounts);

    Orders.setText("Orders");
    jMenuItem15.setText("Check New Releases");
    Orders.add(jMenuItem15);

    jMenuItem16.setText("Order New Videos");
    Orders.add(jMenuItem16);

    jMenuItem17.setText("Order Other Inventory");
    Orders.add(jMenuItem17);

    jMenuItem18.setText("Check-in Received Videos");
    Orders.add(jMenuItem18);

    jMenuItem19.setText("Transfer Inventory From Rental to Sale");
    Orders.add(jMenuItem19);

    mainMenuBar.add(Orders);

    Reports.setText("Reports");
    jMenuItem5.setText("Print Overdue List");
    Reports.add(jMenuItem5);

    Print.setText("Print Rental Inventory");
    Reports.add(Print);

    jMenuItem21.setText("Print For Sale Inventory");
    Reports.add(jMenuItem21);

    jMenuItem22.setText("Print Daily/Weekly/Monthly Revenue");
    Reports.add(jMenuItem22);

    jMenuItem23.setText("Print Rental Statistics");
    Reports.add(jMenuItem23);

    mainMenuBar.add(Reports);

    Help.setText("Help");
    jMenuItem24.setText("About This Program");
    Help.add(jMenuItem24);

    jMenuItem25.setText("Help Topics");
    Help.add(jMenuItem25);

    mainMenuBar.add(Help);

    setJMenuBar(mainMenuBar);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
    this.dispose();
  }//GEN-LAST:event_cancelButtonActionPerformed
  
  private void addModifyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addModifyButtonActionPerformed
    
    // Validate serial number
    //if (!serialNumberDigitCheck()) return;
    //if (!serialNumberUniqueCheck()) return;
    
    if (storeProduct == null){ // This is a new store product
      
      // Save the new store product
      try{
        controller.saveStoreProduct(
                storeBox.getSelectedItem(),
                productBox.getSelectedItem(),
                qohField.getText(),
                reorderPointField.getText(),
                reorderQuantityField.getText());
      } catch(Exception e){
        JOptionPane.showMessageDialog(this, "An error occured while saving store product information.", "Error Saving Store Product", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
      }
      
    } else { // This is an existing store product
      
      // Save the modified store product
      try{
        controller.saveStoreProduct(
                storeProduct,
                storeBox.getSelectedItem(),
                productBox.getSelectedItem(),
                qohField.getText(),
                reorderPointField.getText(),
                reorderQuantityField.getText());
      } catch(Exception e){
        JOptionPane.showMessageDialog(this, "An error occured while saving store product information.", "Error Saving Store Product", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
      }
      
    }
    
    // Save successful.  Clean up.
    JOptionPane.showMessageDialog(this, "The store product has been saved." , "Store Product Saved Successfully", JOptionPane.PLAIN_MESSAGE);
    this.dispose(); // dispose of the current window and all its resources
  }//GEN-LAST:event_addModifyButtonActionPerformed
  
  // Clears the sku field    // Returns the video by updating the database
    private void logButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logButtonActionPerformed
      int i = JOptionPane.showConfirmDialog(this, "Do you really want to logout?\n This will close the program."
              , "Login/Logout", JOptionPane.ERROR_MESSAGE);
      if (i == 0){
        System.exit(0);
      }
    }//GEN-LAST:event_logButtonActionPerformed
    
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JMenu Accounts;
  private javax.swing.JMenuItem DeleteAccount;
  private javax.swing.JMenu File;
  private javax.swing.JMenu Help;
  private javax.swing.JMenu Orders;
  private javax.swing.JMenuItem Print;
  private javax.swing.JMenu Rentals;
  private javax.swing.JMenu Reports;
  private javax.swing.JButton addModifyButton;
  private javax.swing.JLabel blockWoodLabel;
  private javax.swing.JButton cancelButton;
  private javax.swing.JMenuItem checkInVideo;
  private javax.swing.JLabel employeeID;
  private javax.swing.JLabel employeeIDLabel;
  private javax.swing.JLabel employeeName;
  private javax.swing.JMenuItem exit;
  private javax.swing.JLabel group1aLabel;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JMenuItem jMenuItem10;
  private javax.swing.JMenuItem jMenuItem11;
  private javax.swing.JMenuItem jMenuItem12;
  private javax.swing.JMenuItem jMenuItem13;
  private javax.swing.JMenuItem jMenuItem14;
  private javax.swing.JMenuItem jMenuItem15;
  private javax.swing.JMenuItem jMenuItem16;
  private javax.swing.JMenuItem jMenuItem17;
  private javax.swing.JMenuItem jMenuItem18;
  private javax.swing.JMenuItem jMenuItem19;
  private javax.swing.JMenuItem jMenuItem21;
  private javax.swing.JMenuItem jMenuItem22;
  private javax.swing.JMenuItem jMenuItem23;
  private javax.swing.JMenuItem jMenuItem24;
  private javax.swing.JMenuItem jMenuItem25;
  private javax.swing.JMenuItem jMenuItem5;
  private javax.swing.JMenuItem jMenuItem9;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JSeparator jSeparator1;
  private javax.swing.JSeparator jSeparator2;
  private javax.swing.JSeparator jSeparator4;
  private javax.swing.JToggleButton logButton;
  private javax.swing.JLabel logLabel;
  private javax.swing.JPanel logPanel;
  private javax.swing.JMenuItem login;
  private javax.swing.JMenuItem logout;
  private javax.swing.JPanel mainLabelPanel;
  private javax.swing.JMenuBar mainMenuBar;
  private javax.swing.JPanel mainPanel;
  private javax.swing.JScrollPane mainScrollPanel;
  private javax.swing.JMenuItem movieAvailability;
  private javax.swing.JComboBox productBox;
  private javax.swing.JMenuItem properties;
  private javax.swing.JTextField qohField;
  private javax.swing.JTextField reorderPointField;
  private javax.swing.JTextField reorderQuantityField;
  private javax.swing.JMenuItem reserveMovie;
  private javax.swing.JComboBox storeBox;
  private javax.swing.JMenuItem transaction;
  private javax.swing.JPanel transactionPanel;
  // End of variables declaration//GEN-END:variables
  
}
