/*
 * GUIDBMStoreProductDisplay.java
 *
 * This class displays current store-product info and provides
 * navigation to add or modify store-product records.
 */

package edu.byu.isys413.group1a.intex2.GUIs;
import edu.byu.isys413.group1a.intex2.Controllers.DBMStoreProductController;
import javax.swing.UIManager;
import javax.swing.JOptionPane;

/**
 *
 * @author Aaron Hardy, Section 1A, me@aaronhardy.com
 *
 */
public class GUIDBMStoreProductDisplay extends javax.swing.JFrame {
  
  private DBMStoreProductController controller = new DBMStoreProductController(this);
  
  /** Creates new form MainFrameTransaction */
  public GUIDBMStoreProductDisplay() {
    
    /* Sets the GUI to the system look and feel  */
    try {
      UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
    } catch (Exception e) {
      System.err.println("Error loading look and feel: " + e);
    }
    
    initComponents();
    setDisplayTableModel();
  }
  
  /** Sets the model for the display table. */
  public void setDisplayTableModel(){
    try {
      displayTable.setModel(controller.getDBModel());
    } catch(Exception e) {
      JOptionPane.showMessageDialog(this, "An error occured while retrieving dabatase information", "Database Retrieval Error", JOptionPane.ERROR_MESSAGE);
      e.printStackTrace();
    }
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
  private void initComponents() {
    mainScrollPanel = new javax.swing.JScrollPane();
    jPanel1 = new javax.swing.JPanel();
    mainPanel = new javax.swing.JPanel();
    transactionPanel = new javax.swing.JPanel();
    jScrollPane1 = new javax.swing.JScrollPane();
    displayTable = new javax.swing.JTable();
    addButton = new javax.swing.JButton();
    modifyButton = new javax.swing.JButton();
    mainLabelPanel = new javax.swing.JPanel();
    blockWoodLabel = new javax.swing.JLabel();
    logPanel = new javax.swing.JPanel();
    logLabel = new javax.swing.JLabel();
    jSeparator1 = new javax.swing.JSeparator();
    employeeName = new javax.swing.JLabel();
    jSeparator2 = new javax.swing.JSeparator();
    employeeIDLabel = new javax.swing.JLabel();
    employeeID = new javax.swing.JLabel();
    jSeparator4 = new javax.swing.JSeparator();
    logButton = new javax.swing.JToggleButton();
    group1aLabel = new javax.swing.JLabel();
    mainMenuBar = new javax.swing.JMenuBar();
    File = new javax.swing.JMenu();
    login = new javax.swing.JMenuItem();
    logout = new javax.swing.JMenuItem();
    properties = new javax.swing.JMenuItem();
    exit = new javax.swing.JMenuItem();
    Rentals = new javax.swing.JMenu();
    transaction = new javax.swing.JMenuItem();
    checkInVideo = new javax.swing.JMenuItem();
    movieAvailability = new javax.swing.JMenuItem();
    reserveMovie = new javax.swing.JMenuItem();
    Accounts = new javax.swing.JMenu();
    jMenuItem9 = new javax.swing.JMenuItem();
    jMenuItem10 = new javax.swing.JMenuItem();
    jMenuItem11 = new javax.swing.JMenuItem();
    jMenuItem12 = new javax.swing.JMenuItem();
    jMenuItem13 = new javax.swing.JMenuItem();
    jMenuItem14 = new javax.swing.JMenuItem();
    DeleteAccount = new javax.swing.JMenuItem();
    Orders = new javax.swing.JMenu();
    jMenuItem15 = new javax.swing.JMenuItem();
    jMenuItem16 = new javax.swing.JMenuItem();
    jMenuItem17 = new javax.swing.JMenuItem();
    jMenuItem18 = new javax.swing.JMenuItem();
    jMenuItem19 = new javax.swing.JMenuItem();
    Reports = new javax.swing.JMenu();
    jMenuItem5 = new javax.swing.JMenuItem();
    Print = new javax.swing.JMenuItem();
    jMenuItem21 = new javax.swing.JMenuItem();
    jMenuItem22 = new javax.swing.JMenuItem();
    jMenuItem23 = new javax.swing.JMenuItem();
    Help = new javax.swing.JMenu();
    jMenuItem24 = new javax.swing.JMenuItem();
    jMenuItem25 = new javax.swing.JMenuItem();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("BlockWoodVideo");
    setBackground(new java.awt.Color(255, 255, 255));
    transactionPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("DB Maintenance"));
    displayTable.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null}
      },
      new String [] {
        "Title 1", "Title 2", "Title 3", "Title 4"
      }
    ));
    jScrollPane1.setViewportView(displayTable);

    org.jdesktop.layout.GroupLayout transactionPanelLayout = new org.jdesktop.layout.GroupLayout(transactionPanel);
    transactionPanel.setLayout(transactionPanelLayout);
    transactionPanelLayout.setHorizontalGroup(
      transactionPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 812, Short.MAX_VALUE)
    );
    transactionPanelLayout.setVerticalGroup(
      transactionPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(org.jdesktop.layout.GroupLayout.TRAILING, jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
    );

    addButton.setText("Add Store Product");
    addButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        addButtonActionPerformed(evt);
      }
    });

    modifyButton.setText("Modify Store Product");
    modifyButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        modifyButtonActionPerformed(evt);
      }
    });

    org.jdesktop.layout.GroupLayout mainPanelLayout = new org.jdesktop.layout.GroupLayout(mainPanel);
    mainPanel.setLayout(mainPanelLayout);
    mainPanelLayout.setHorizontalGroup(
      mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(mainPanelLayout.createSequentialGroup()
        .add(mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
          .add(mainPanelLayout.createSequentialGroup()
            .addContainerGap()
            .add(transactionPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          .add(mainPanelLayout.createSequentialGroup()
            .add(300, 300, 300)
            .add(addButton)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(modifyButton)))
        .addContainerGap())
    );
    mainPanelLayout.setVerticalGroup(
      mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(mainPanelLayout.createSequentialGroup()
        .add(21, 21, 21)
        .add(mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(addButton)
          .add(modifyButton))
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(transactionPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(33, Short.MAX_VALUE))
    );
    jPanel1.add(mainPanel);

    mainScrollPanel.setViewportView(jPanel1);

    getContentPane().add(mainScrollPanel, java.awt.BorderLayout.CENTER);

    mainLabelPanel.setLayout(new java.awt.BorderLayout());

    mainLabelPanel.setAutoscrolls(true);
    blockWoodLabel.setBackground(new java.awt.Color(204, 0, 51));
    blockWoodLabel.setFont(new java.awt.Font("Monotype Corsiva", 0, 36));
    blockWoodLabel.setForeground(new java.awt.Color(255, 255, 255));
    blockWoodLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    blockWoodLabel.setText("BlockWood Video Inventory Management");
    blockWoodLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    blockWoodLabel.setMaximumSize(new java.awt.Dimension(627, 45));
    blockWoodLabel.setOpaque(true);
    blockWoodLabel.setPreferredSize(new java.awt.Dimension(412, 50));
    mainLabelPanel.add(blockWoodLabel, java.awt.BorderLayout.NORTH);

    logPanel.setBackground(new java.awt.Color(204, 0, 51));
    logPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
    logPanel.setForeground(new java.awt.Color(255, 255, 255));
    logPanel.setMinimumSize(new java.awt.Dimension(155, 41));
    logPanel.setPreferredSize(new java.awt.Dimension(155, 41));
    logLabel.setBackground(new java.awt.Color(215, 214, 214));
    logLabel.setForeground(new java.awt.Color(255, 255, 255));
    logLabel.setText("Logged in as:");
    logPanel.add(logLabel);

    jSeparator1.setBackground(new java.awt.Color(204, 0, 51));
    jSeparator1.setForeground(new java.awt.Color(204, 0, 51));
    jSeparator1.setPreferredSize(new java.awt.Dimension(25, 10));
    logPanel.add(jSeparator1);

    employeeName.setBackground(new java.awt.Color(215, 214, 214));
    employeeName.setForeground(new java.awt.Color(255, 255, 255));
    employeeName.setText("James Christensen");
    logPanel.add(employeeName);

    jSeparator2.setBackground(new java.awt.Color(204, 0, 51));
    jSeparator2.setForeground(new java.awt.Color(204, 0, 51));
    jSeparator2.setPreferredSize(new java.awt.Dimension(25, 10));
    logPanel.add(jSeparator2);

    employeeIDLabel.setForeground(new java.awt.Color(255, 255, 255));
    employeeIDLabel.setText("Employee ID:");
    logPanel.add(employeeIDLabel);

    employeeID.setForeground(new java.awt.Color(255, 255, 255));
    employeeID.setText("788997");
    logPanel.add(employeeID);

    jSeparator4.setBackground(new java.awt.Color(204, 0, 51));
    jSeparator4.setForeground(new java.awt.Color(204, 0, 51));
    jSeparator4.setPreferredSize(new java.awt.Dimension(25, 10));
    logPanel.add(jSeparator4);

    logButton.setText("Logout");
    logButton.setToolTipText("Logout Current User");
    logButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        logButtonActionPerformed(evt);
      }
    });

    logPanel.add(logButton);

    mainLabelPanel.add(logPanel, java.awt.BorderLayout.SOUTH);

    getContentPane().add(mainLabelPanel, java.awt.BorderLayout.NORTH);

    group1aLabel.setBackground(new java.awt.Color(204, 0, 51));
    group1aLabel.setForeground(new java.awt.Color(255, 255, 255));
    group1aLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    group1aLabel.setText("Created by Group 1A");
    group1aLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    group1aLabel.setMinimumSize(new java.awt.Dimension(100, 25));
    group1aLabel.setOpaque(true);
    group1aLabel.setPreferredSize(new java.awt.Dimension(100, 25));
    getContentPane().add(group1aLabel, java.awt.BorderLayout.SOUTH);

    File.setText("File");
    login.setText("Login");
    File.add(login);

    logout.setText("Logout");
    File.add(logout);

    properties.setText("Properties");
    File.add(properties);

    exit.setText("Exit");
    File.add(exit);

    mainMenuBar.add(File);

    Rentals.setText("Rentals");
    transaction.setText("Make Another Transaction");
    Rentals.add(transaction);

    checkInVideo.setText("Check-in Video");
    Rentals.add(checkInVideo);

    movieAvailability.setText("Check Movie Availability");
    Rentals.add(movieAvailability);

    reserveMovie.setText("Reserve Movie");
    Rentals.add(reserveMovie);

    mainMenuBar.add(Rentals);

    Accounts.setText("Accounts");
    jMenuItem9.setText("Create Customer Membership");
    Accounts.add(jMenuItem9);

    jMenuItem10.setText("Create Customer Account");
    Accounts.add(jMenuItem10);

    jMenuItem11.setText("Update Customer Account");
    Accounts.add(jMenuItem11);

    jMenuItem12.setText("Add Membership to Account");
    Accounts.add(jMenuItem12);

    jMenuItem13.setText("Reissue Membership Card");
    Accounts.add(jMenuItem13);

    jMenuItem14.setText("Search for Account");
    Accounts.add(jMenuItem14);

    DeleteAccount.setLabel("Delete Account");
    Accounts.add(DeleteAccount);

    mainMenuBar.add(Accounts);

    Orders.setText("Orders");
    jMenuItem15.setText("Check New Releases");
    Orders.add(jMenuItem15);

    jMenuItem16.setText("Order New Videos");
    Orders.add(jMenuItem16);

    jMenuItem17.setText("Order Other Inventory");
    Orders.add(jMenuItem17);

    jMenuItem18.setText("Check-in Received Videos");
    Orders.add(jMenuItem18);

    jMenuItem19.setText("Transfer Inventory From Rental to Sale");
    Orders.add(jMenuItem19);

    mainMenuBar.add(Orders);

    Reports.setText("Reports");
    jMenuItem5.setText("Print Overdue List");
    Reports.add(jMenuItem5);

    Print.setText("Print Rental Inventory");
    Reports.add(Print);

    jMenuItem21.setText("Print For Sale Inventory");
    Reports.add(jMenuItem21);

    jMenuItem22.setText("Print Daily/Weekly/Monthly Revenue");
    Reports.add(jMenuItem22);

    jMenuItem23.setText("Print Rental Statistics");
    Reports.add(jMenuItem23);

    mainMenuBar.add(Reports);

    Help.setText("Help");
    jMenuItem24.setText("About This Program");
    Help.add(jMenuItem24);

    jMenuItem25.setText("Help Topics");
    Help.add(jMenuItem25);

    mainMenuBar.add(Help);

    setJMenuBar(mainMenuBar);

    pack();
  }// </editor-fold>//GEN-END:initComponents
  
  /** Opens window for modifying record */
  private void modifyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyButtonActionPerformed
    if (displayTable.getSelectedRow() != -1){
      GUIDBMStoreProductForm form = new GUIDBMStoreProductForm(this, controller, displayTable.getSelectedRow());
      form.setVisible(true);
    } else {
      JOptionPane.showMessageDialog(this, "You must select a store product to modify.", "No Selection Made", JOptionPane.ERROR_MESSAGE);
    }
  }//GEN-LAST:event_modifyButtonActionPerformed
  
  /** Opens window for adding record */
  private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
    GUIDBMStoreProductForm form = new GUIDBMStoreProductForm(this, controller);
    form.setVisible(true);
  }//GEN-LAST:event_addButtonActionPerformed
    
  // Clears the sku field    // Returns the video by updating the database
    private void logButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logButtonActionPerformed
      int i = JOptionPane.showConfirmDialog(this, "Do you really want to logout?\n This will close the program."
              , "Login/Logout", JOptionPane.ERROR_MESSAGE);
      if (i == 0){
        System.exit(0);
      }
    }//GEN-LAST:event_logButtonActionPerformed

    
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JMenu Accounts;
  private javax.swing.JMenuItem DeleteAccount;
  private javax.swing.JMenu File;
  private javax.swing.JMenu Help;
  private javax.swing.JMenu Orders;
  private javax.swing.JMenuItem Print;
  private javax.swing.JMenu Rentals;
  private javax.swing.JMenu Reports;
  private javax.swing.JButton addButton;
  private javax.swing.JLabel blockWoodLabel;
  private javax.swing.JMenuItem checkInVideo;
  private javax.swing.JTable displayTable;
  private javax.swing.JLabel employeeID;
  private javax.swing.JLabel employeeIDLabel;
  private javax.swing.JLabel employeeName;
  private javax.swing.JMenuItem exit;
  private javax.swing.JLabel group1aLabel;
  private javax.swing.JMenuItem jMenuItem10;
  private javax.swing.JMenuItem jMenuItem11;
  private javax.swing.JMenuItem jMenuItem12;
  private javax.swing.JMenuItem jMenuItem13;
  private javax.swing.JMenuItem jMenuItem14;
  private javax.swing.JMenuItem jMenuItem15;
  private javax.swing.JMenuItem jMenuItem16;
  private javax.swing.JMenuItem jMenuItem17;
  private javax.swing.JMenuItem jMenuItem18;
  private javax.swing.JMenuItem jMenuItem19;
  private javax.swing.JMenuItem jMenuItem21;
  private javax.swing.JMenuItem jMenuItem22;
  private javax.swing.JMenuItem jMenuItem23;
  private javax.swing.JMenuItem jMenuItem24;
  private javax.swing.JMenuItem jMenuItem25;
  private javax.swing.JMenuItem jMenuItem5;
  private javax.swing.JMenuItem jMenuItem9;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JSeparator jSeparator1;
  private javax.swing.JSeparator jSeparator2;
  private javax.swing.JSeparator jSeparator4;
  private javax.swing.JToggleButton logButton;
  private javax.swing.JLabel logLabel;
  private javax.swing.JPanel logPanel;
  private javax.swing.JMenuItem login;
  private javax.swing.JMenuItem logout;
  private javax.swing.JPanel mainLabelPanel;
  private javax.swing.JMenuBar mainMenuBar;
  private javax.swing.JPanel mainPanel;
  private javax.swing.JScrollPane mainScrollPanel;
  private javax.swing.JButton modifyButton;
  private javax.swing.JMenuItem movieAvailability;
  private javax.swing.JMenuItem properties;
  private javax.swing.JMenuItem reserveMovie;
  private javax.swing.JMenuItem transaction;
  private javax.swing.JPanel transactionPanel;
  // End of variables declaration//GEN-END:variables
  
}
