/*
 * MainFrameTransaction.java
 *
 * Created on September 16, 2005, 3:11 PM
 * This program will interface with the user in form of a GUI to return a video.
 * The user scans or types in the sku # on the video, then the system process the rental video.
 * If the video is not late, the status of the video is changed to in.
 * If the video is late, a transaction is made and the customer's account balance is updated in
 * the database to reflect the late charges.
 */

package edu.byu.isys413.group1a.intex2.GUIs;
import edu.byu.isys413.group1a.intex2.Controllers.RenewalBatch;
import edu.byu.isys413.group1a.intex2.Controllers.ReturnVideoController;
import edu.byu.isys413.group1a.intex2.Misc.RenewalException;
import javax.swing.UIManager;
import javax.swing.JOptionPane;

/**
 *
 * @author Group 1A
 *
 */
public class GUIReturnRental extends javax.swing.JFrame {
  
  private ReturnVideoController rvc = new ReturnVideoController();
  /** Creates new form MainFrameTransaction */
  public GUIReturnRental() {
    
    /* Sets the GUI to the system look and feel  */
    try {
      UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
    } catch (Exception e) {
      System.err.println("Error loading look and feel: " + e);
    }
    
    initComponents();
    skuTextField.requestFocus();
  }
  
  private void notSavedMessage(){
    JOptionPane.showMessageDialog(this, "An ERROR occurred while saving the return.\n" +
            "Pleaese try again, check video history, and then talk to the manager.","RETURN NOT SAVED", JOptionPane.ERROR_MESSAGE);
  }
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
  private void initComponents() {
    mainScrollPanel = new javax.swing.JScrollPane();
    jPanel1 = new javax.swing.JPanel();
    mainPanel = new javax.swing.JPanel();
    transactionPanel = new javax.swing.JPanel();
    skuTextField = new javax.swing.JTextField();
    lookupItem = new javax.swing.JButton();
    returnRental = new javax.swing.JButton();
    skuLabel = new javax.swing.JLabel();
    jButton1 = new javax.swing.JButton();
    mainLabelPanel = new javax.swing.JPanel();
    blockWoodLabel = new javax.swing.JLabel();
    logPanel = new javax.swing.JPanel();
    logLabel = new javax.swing.JLabel();
    jSeparator1 = new javax.swing.JSeparator();
    employeeName = new javax.swing.JLabel();
    jSeparator2 = new javax.swing.JSeparator();
    employeeIDLabel = new javax.swing.JLabel();
    employeeID = new javax.swing.JLabel();
    jSeparator4 = new javax.swing.JSeparator();
    logButton = new javax.swing.JToggleButton();
    group1aLabel = new javax.swing.JLabel();
    mainMenuBar = new javax.swing.JMenuBar();
    File = new javax.swing.JMenu();
    login = new javax.swing.JMenuItem();
    logout = new javax.swing.JMenuItem();
    properties = new javax.swing.JMenuItem();
    exit = new javax.swing.JMenuItem();
    Rentals = new javax.swing.JMenu();
    transaction = new javax.swing.JMenuItem();
    checkInVideo = new javax.swing.JMenuItem();
    movieAvailability = new javax.swing.JMenuItem();
    reserveMovie = new javax.swing.JMenuItem();
    Accounts = new javax.swing.JMenu();
    createAccount = new javax.swing.JMenuItem();
    addCustomer = new javax.swing.JMenuItem();
    updateAccount = new javax.swing.JMenuItem();
    buyMembership = new javax.swing.JMenuItem();
    renewMembership = new javax.swing.JMenuItem();
    DeleteAccount = new javax.swing.JMenuItem();
    Orders = new javax.swing.JMenu();
    jMenuItem15 = new javax.swing.JMenuItem();
    jMenuItem16 = new javax.swing.JMenuItem();
    jMenuItem17 = new javax.swing.JMenuItem();
    jMenuItem18 = new javax.swing.JMenuItem();
    jMenuItem19 = new javax.swing.JMenuItem();
    Reports = new javax.swing.JMenu();
    jMenuItem5 = new javax.swing.JMenuItem();
    Print = new javax.swing.JMenuItem();
    jMenuItem21 = new javax.swing.JMenuItem();
    jMenuItem22 = new javax.swing.JMenuItem();
    jMenuItem23 = new javax.swing.JMenuItem();
    Help = new javax.swing.JMenu();
    jMenuItem24 = new javax.swing.JMenuItem();
    jMenuItem25 = new javax.swing.JMenuItem();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("BlockWoodVideo");
    setBackground(new java.awt.Color(255, 255, 255));
    transactionPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Rental Return"));
    skuTextField.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        skuTextFieldActionPerformed(evt);
      }
    });

    lookupItem.setIcon(new javax.swing.ImageIcon("C:\\Documents and Settings\\James\\Desktop\\lookup_icon.gif"));
    lookupItem.setToolTipText("Lookup Rental History");
    lookupItem.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        lookupItemActionPerformed(evt);
      }
    });

    returnRental.setText("Return Rental Video");
    returnRental.setToolTipText("Return Video");
    returnRental.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        returnRentalActionPerformed(evt);
      }
    });

    skuLabel.setFont(new java.awt.Font("Tahoma", 1, 14));
    skuLabel.setText("Serial #");

    jButton1.setText("Clear Field");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });

    org.jdesktop.layout.GroupLayout transactionPanelLayout = new org.jdesktop.layout.GroupLayout(transactionPanel);
    transactionPanel.setLayout(transactionPanelLayout);
    transactionPanelLayout.setHorizontalGroup(
      transactionPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(transactionPanelLayout.createSequentialGroup()
        .addContainerGap()
        .add(transactionPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
          .add(org.jdesktop.layout.GroupLayout.LEADING, skuLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
          .add(org.jdesktop.layout.GroupLayout.LEADING, transactionPanelLayout.createSequentialGroup()
            .add(skuTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 143, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(returnRental)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 42, Short.MAX_VALUE)
            .add(jButton1)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(lookupItem)))
        .addContainerGap())
    );
    transactionPanelLayout.setVerticalGroup(
      transactionPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(transactionPanelLayout.createSequentialGroup()
        .addContainerGap()
        .add(skuLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 27, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(transactionPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(skuTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
          .add(returnRental)
          .add(jButton1)
          .add(lookupItem))
        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    org.jdesktop.layout.GroupLayout mainPanelLayout = new org.jdesktop.layout.GroupLayout(mainPanel);
    mainPanel.setLayout(mainPanelLayout);
    mainPanelLayout.setHorizontalGroup(
      mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(mainPanelLayout.createSequentialGroup()
        .add(135, 135, 135)
        .add(transactionPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(217, Short.MAX_VALUE))
    );
    mainPanelLayout.setVerticalGroup(
      mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(mainPanelLayout.createSequentialGroup()
        .add(95, 95, 95)
        .add(transactionPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(363, Short.MAX_VALUE))
    );
    jPanel1.add(mainPanel);

    mainScrollPanel.setViewportView(jPanel1);

    getContentPane().add(mainScrollPanel, java.awt.BorderLayout.CENTER);

    mainLabelPanel.setLayout(new java.awt.BorderLayout());

    mainLabelPanel.setAutoscrolls(true);
    blockWoodLabel.setBackground(new java.awt.Color(204, 0, 51));
    blockWoodLabel.setFont(new java.awt.Font("Monotype Corsiva", 0, 36));
    blockWoodLabel.setForeground(new java.awt.Color(255, 255, 255));
    blockWoodLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    blockWoodLabel.setText("BlockWood Video Rental Return");
    blockWoodLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    blockWoodLabel.setMaximumSize(new java.awt.Dimension(627, 45));
    blockWoodLabel.setOpaque(true);
    blockWoodLabel.setPreferredSize(new java.awt.Dimension(412, 50));
    mainLabelPanel.add(blockWoodLabel, java.awt.BorderLayout.NORTH);

    logPanel.setBackground(new java.awt.Color(204, 0, 51));
    logPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
    logPanel.setForeground(new java.awt.Color(255, 255, 255));
    logPanel.setMinimumSize(new java.awt.Dimension(155, 41));
    logPanel.setPreferredSize(new java.awt.Dimension(155, 41));
    logLabel.setBackground(new java.awt.Color(215, 214, 214));
    logLabel.setForeground(new java.awt.Color(255, 255, 255));
    logLabel.setText("Logged in as:");
    logPanel.add(logLabel);

    jSeparator1.setBackground(new java.awt.Color(204, 0, 51));
    jSeparator1.setForeground(new java.awt.Color(204, 0, 51));
    jSeparator1.setPreferredSize(new java.awt.Dimension(25, 10));
    logPanel.add(jSeparator1);

    employeeName.setBackground(new java.awt.Color(215, 214, 214));
    employeeName.setForeground(new java.awt.Color(255, 255, 255));
    employeeName.setText("James Christensen");
    logPanel.add(employeeName);

    jSeparator2.setBackground(new java.awt.Color(204, 0, 51));
    jSeparator2.setForeground(new java.awt.Color(204, 0, 51));
    jSeparator2.setPreferredSize(new java.awt.Dimension(25, 10));
    logPanel.add(jSeparator2);

    employeeIDLabel.setForeground(new java.awt.Color(255, 255, 255));
    employeeIDLabel.setText("Employee ID:");
    logPanel.add(employeeIDLabel);

    employeeID.setForeground(new java.awt.Color(255, 255, 255));
    employeeID.setText("788997");
    logPanel.add(employeeID);

    jSeparator4.setBackground(new java.awt.Color(204, 0, 51));
    jSeparator4.setForeground(new java.awt.Color(204, 0, 51));
    jSeparator4.setPreferredSize(new java.awt.Dimension(25, 10));
    logPanel.add(jSeparator4);

    logButton.setText("Logout");
    logButton.setToolTipText("Logout Current User");
    logButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        logButtonActionPerformed(evt);
      }
    });

    logPanel.add(logButton);

    mainLabelPanel.add(logPanel, java.awt.BorderLayout.SOUTH);

    getContentPane().add(mainLabelPanel, java.awt.BorderLayout.NORTH);

    group1aLabel.setBackground(new java.awt.Color(204, 0, 51));
    group1aLabel.setForeground(new java.awt.Color(255, 255, 255));
    group1aLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    group1aLabel.setText("Created by Group 1A");
    group1aLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    group1aLabel.setMinimumSize(new java.awt.Dimension(100, 25));
    group1aLabel.setOpaque(true);
    group1aLabel.setPreferredSize(new java.awt.Dimension(100, 25));
    getContentPane().add(group1aLabel, java.awt.BorderLayout.SOUTH);

    File.setText("File");
    login.setText("Login");
    File.add(login);

    logout.setText("Logout");
    File.add(logout);

    properties.setText("Properties");
    File.add(properties);

    exit.setText("Exit");
    File.add(exit);

    mainMenuBar.add(File);

    Rentals.setText("Rentals");
    transaction.setText("Make Another Transaction");
    Rentals.add(transaction);

    checkInVideo.setText("Check-in Video");
    Rentals.add(checkInVideo);

    movieAvailability.setText("Check Movie Availability");
    Rentals.add(movieAvailability);

    reserveMovie.setText("Reserve Movie");
    Rentals.add(reserveMovie);

    mainMenuBar.add(Rentals);

    Accounts.setText("Accounts");
    createAccount.setText("Create New Account");
    createAccount.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        createAccountActionPerformed(evt);
      }
    });

    Accounts.add(createAccount);

    addCustomer.setText("Add Customer to Existing Account");
    addCustomer.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        addCustomerActionPerformed(evt);
      }
    });

    Accounts.add(addCustomer);

    updateAccount.setText("Update Customer Account");
    Accounts.add(updateAccount);

    buyMembership.setText("Buy Membership");
    buyMembership.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        buyMembershipActionPerformed(evt);
      }
    });

    Accounts.add(buyMembership);

    renewMembership.setText("Renew Expired Memberships");
    renewMembership.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        renewMembershipActionPerformed(evt);
      }
    });

    Accounts.add(renewMembership);

    DeleteAccount.setLabel("Delete Account");
    Accounts.add(DeleteAccount);

    mainMenuBar.add(Accounts);

    Orders.setText("Orders");
    jMenuItem15.setText("Check New Releases");
    Orders.add(jMenuItem15);

    jMenuItem16.setText("Order New Videos");
    Orders.add(jMenuItem16);

    jMenuItem17.setText("Order Other Inventory");
    Orders.add(jMenuItem17);

    jMenuItem18.setText("Check-in Received Videos");
    Orders.add(jMenuItem18);

    jMenuItem19.setText("Transfer Inventory From Rental to Sale");
    Orders.add(jMenuItem19);

    mainMenuBar.add(Orders);

    Reports.setText("Reports");
    jMenuItem5.setText("Print Overdue List");
    Reports.add(jMenuItem5);

    Print.setText("Print Rental Inventory");
    Reports.add(Print);

    jMenuItem21.setText("Print For Sale Inventory");
    Reports.add(jMenuItem21);

    jMenuItem22.setText("Print Daily/Weekly/Monthly Revenue");
    Reports.add(jMenuItem22);

    jMenuItem23.setText("Print Rental Statistics");
    Reports.add(jMenuItem23);

    mainMenuBar.add(Reports);

    Help.setText("Help");
    jMenuItem24.setText("About This Program");
    Help.add(jMenuItem24);

    jMenuItem25.setText("Help Topics");
    Help.add(jMenuItem25);

    mainMenuBar.add(Help);

    setJMenuBar(mainMenuBar);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void renewMembershipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_renewMembershipActionPerformed
    try{
      RenewalBatch rb = new RenewalBatch();
      rb.RenewMemberships();
      JOptionPane.showMessageDialog(this,"The expired memberships have been renewed.", "Membership Renewal", JOptionPane.INFORMATION_MESSAGE);
    } catch(RenewalException e1 ){
      JOptionPane.showMessageDialog(this, e1.getMessage(), "Membership Renewal Error", JOptionPane.ERROR_MESSAGE);
    } catch(Exception e ){
      JOptionPane.showMessageDialog(this, "An error occured while the renewing the expired memberships.\n" + e.getMessage(), "Membership Renewal Error", JOptionPane.ERROR_MESSAGE);
    }
  }//GEN-LAST:event_renewMembershipActionPerformed

  private void buyMembershipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyMembershipActionPerformed
//here we can have a box ask which kind of membership and set the sku and add it if a customer is selected
  }//GEN-LAST:event_buyMembershipActionPerformed

  private void addCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerActionPerformed
    GUIAcctManagement guiAcctManage = new GUIAcctManagement();
    guiAcctManage.setVisible(true);
  }//GEN-LAST:event_addCustomerActionPerformed

  private void createAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccountActionPerformed
    GUIAcctManagement guiAcctManage = new GUIAcctManagement();
    guiAcctManage.setVisible(true);
  }//GEN-LAST:event_createAccountActionPerformed
    
    private void skuTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skuTextFieldActionPerformed
      returnRentalActionPerformed(evt);
    }//GEN-LAST:event_skuTextFieldActionPerformed
    
    // Clears the sku field
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      skuTextField.setText("");
      skuTextField.requestFocus();
    }//GEN-LAST:event_jButton1ActionPerformed
    // Returns the video by updating the database
    private void returnRentalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnRentalActionPerformed
      if (skuTextField.getText().length()==8){
        try{
          rvc.returnVideo(skuTextField.getText());
          JOptionPane.showMessageDialog(this, "Rental has been returned successfully.");
          skuTextField.setText("");
        } catch (Exception e){
          JOptionPane.showMessageDialog(this, "An error was encountered while saving the rental return.", "Error Saving Rental Return", JOptionPane.ERROR_MESSAGE);
        }
      } else {
        JOptionPane.showMessageDialog(this, "The serial number you entered is invalid.", "Invalid Serial Number", JOptionPane.ERROR_MESSAGE);
      }
      
    }//GEN-LAST:event_returnRentalActionPerformed
    
    private void lookupItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lookupItemActionPerformed
      JOptionPane.showMessageDialog(this, "Currently, this function is not available.", "Lookup Product Item", JOptionPane.PLAIN_MESSAGE);
      skuTextField.requestFocus();
    }//GEN-LAST:event_lookupItemActionPerformed
    
    private void logButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logButtonActionPerformed
      int i = JOptionPane.showConfirmDialog(this, "Do you really want to logout?\n This will close the program."
              , "Login/Logout", JOptionPane.ERROR_MESSAGE);
      if (i == 0){
        System.exit(0);
      }
    }//GEN-LAST:event_logButtonActionPerformed
    /**
     * @param args the command line arguments
     * This runs the mainframe and makes it visible
     */
    public static void MainFrameReturnRental(String args[]) {
      java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
          new GUIReturnRental().setVisible(true);
        }
      });
    }
    
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JMenu Accounts;
  private javax.swing.JMenuItem DeleteAccount;
  private javax.swing.JMenu File;
  private javax.swing.JMenu Help;
  private javax.swing.JMenu Orders;
  private javax.swing.JMenuItem Print;
  private javax.swing.JMenu Rentals;
  private javax.swing.JMenu Reports;
  private javax.swing.JMenuItem addCustomer;
  private javax.swing.JLabel blockWoodLabel;
  private javax.swing.JMenuItem buyMembership;
  private javax.swing.JMenuItem checkInVideo;
  private javax.swing.JMenuItem createAccount;
  private javax.swing.JLabel employeeID;
  private javax.swing.JLabel employeeIDLabel;
  private javax.swing.JLabel employeeName;
  private javax.swing.JMenuItem exit;
  private javax.swing.JLabel group1aLabel;
  private javax.swing.JButton jButton1;
  private javax.swing.JMenuItem jMenuItem15;
  private javax.swing.JMenuItem jMenuItem16;
  private javax.swing.JMenuItem jMenuItem17;
  private javax.swing.JMenuItem jMenuItem18;
  private javax.swing.JMenuItem jMenuItem19;
  private javax.swing.JMenuItem jMenuItem21;
  private javax.swing.JMenuItem jMenuItem22;
  private javax.swing.JMenuItem jMenuItem23;
  private javax.swing.JMenuItem jMenuItem24;
  private javax.swing.JMenuItem jMenuItem25;
  private javax.swing.JMenuItem jMenuItem5;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JSeparator jSeparator1;
  private javax.swing.JSeparator jSeparator2;
  private javax.swing.JSeparator jSeparator4;
  private javax.swing.JToggleButton logButton;
  private javax.swing.JLabel logLabel;
  private javax.swing.JPanel logPanel;
  private javax.swing.JMenuItem login;
  private javax.swing.JMenuItem logout;
  private javax.swing.JButton lookupItem;
  private javax.swing.JPanel mainLabelPanel;
  private javax.swing.JMenuBar mainMenuBar;
  private javax.swing.JPanel mainPanel;
  private javax.swing.JScrollPane mainScrollPanel;
  private javax.swing.JMenuItem movieAvailability;
  private javax.swing.JMenuItem properties;
  private javax.swing.JMenuItem renewMembership;
  private javax.swing.JMenuItem reserveMovie;
  private javax.swing.JButton returnRental;
  private javax.swing.JLabel skuLabel;
  private javax.swing.JTextField skuTextField;
  private javax.swing.JMenuItem transaction;
  private javax.swing.JPanel transactionPanel;
  private javax.swing.JMenuItem updateAccount;
  // End of variables declaration//GEN-END:variables
    
}
